name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container:
          image: cuaesd/aesd-autotest:24-assignment4-buildroot
          options: --platform linux/amd64
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - name: Clone repository
            run: |
              find . -mindepth 1 -delete 2>/dev/null || true
              git clone "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" .
              git checkout "$GITHUB_SHA"
              git submodule update --init --recursive
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - name: Start SSH agent
            env:
              SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            run: bash .github/actions/ssh-agent.sh
          - name: Run full test
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: ./full-test.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
